const { cmd, commands } = require('../command');
const { getBuffer, getGroupAdmins, getRandom, h2k, isUrl, Json, runtime, sleep, fetchJson } = require('../lib/functions');
const axios = require('axios');

cmd({
    pattern: 'rw2',
    alias: ['randomwall', 'wallpaper'],
    react: '🌌',
    desc: 'Download random wallpapers based on keywords.',
    category: 'wallpapers',
    use: '.rw <keyword>',
    filename: __filename
}, async (m, sock, args, { from, args: query, reply }) => {
    try {
        const keyword = query.split(' ')[0] || 'random';
        const apiUrl = `https://pikabotzapi.vercel.app/random/randomwall/?apikey=anya-md&query=${keyword}`;
        
        const response = await axios.get(apiUrl);
        
        if (response.data.imgUrl) {
            const imageUrl = response.data.imgUrl;
            const caption = `🌌 Random Wallpaper: *${keyword}*\n\n> © Generated By INCONNU-XD`;
            
            await sock.sendMessage(from, {
                image: { url: imageUrl },
                caption: caption
            }, { quoted: m });
        } else {
            reply(`❌ Failed to fetch wallpaper for "${keyword}".`);
        }
    } catch (error) {
        console.error('Error:', error);
        reply('❌ An error occurred while fetching the wallpaper.');
    }
});
